### ISSUE TITLE
How the FAUCET METAMASK works?

### ISSUE THREAD

**Issue by advokardag** [MetaMask/faq#17]
How the FAUCET METAMASK works? I received on my ETH account, but I do not know how to use them. Where can I read how to use it?

**Comment by kumavis** [comment]
You can experiment sending them or using a testnet dapp.  If you'd like to use the mainnet you can change the network in the upper left.

I recommend http://tokenfactory.surge.sh to practice sending txs and creating contracts. Start by creating your own token and then sending it to a 2nd account.

**Comment by flyswatter** [comment]
Ether is like having a subscription to a globally shared computer. You use it by using the Ethereum shared computer.

This may mean you're publishing your own programs, in which case [I will recommend Alex Miller's medium page](https://hackernoon.com/@asmiller1989).

If you're just looking for existing Decentralized Apps (Dapps) to use, I recommend browsing a "Dapp store" like [etherian.world](https://etherian.world/).

I hope that helps, I'm closing this issue for now, since it's not really an issue with our software. For general discussion, [join our slack](http://slack.metamask.io/).
