### ISSUE TITLE
Exception due to a call to et_mining

### ISSUE THREAD

**Issue by imosdevteam** [MetaMask/faq#22]
Running into this error when working on a dapp and testing with metamask.
There is no call in my code to web3.eth.mining yet the exception bellow is thrown by metamask after I run my dapp. Is this a known issue?
Thanks so much!

web3 - 0.19.0
testrpc - 3.0.5

`inpage.js:206 Uncaught Error: The MetaMask Web3 object does not support synchronous methods like eth_mining without a callback parameter. See https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#dizzy-all-async---think-of-metamask-as-a-light-client for details.
    at MetamaskInpageProvider.send (inpage.js:206)
    at Provider.send (contract.js:19)
    at RequestManager.send (requestmanager.js:58)
    at Eth.get [as mining] (property.js:107)
    at derez (<anonymous>:2:6079)
    at derez (<anonymous>:2:6072)
    at derez (<anonymous>:2:6072)
    at derez (<anonymous>:2:6072)
    at derez (<anonymous>:2:6072)
    at derez (<anonymous>:2:6072)`

**Comment by flyswatter** [comment]
The error message is because you're using synchronous methods instead of async.
https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#dizzy-all-async---think-of-metamask-as-a-light-client

I do think we don't support mining methods, but this is not that error. It does look like a portion of your code is calling `eth_mining`:
`Eth.get [as mining] (property.js:107)`

**Comment by flyswatter** [comment]
Also, this is the wrong repository for plugin issues. If this is a real bug, please re-submit to MetaMask/metamask-plugin.

**Comment by imosdevteam** [comment]
Sorry about that - will use the plugin issues tracker.
