### ISSUE TITLE
How do I call web3.eth.getBalance() in metamask?

### ISSUE THREAD

**Issue by IAMtheIAM** [MetaMask/faq#23]
Following the instructions, I added a callback method to make the method async. It logs `e {s: 1, e: 0, c: Array(1)}`

But it says `Cannot read property 'toNumber' of undefined`. So why is it not able to getBalance()?
```

function getBalance (address) {
  return web3.eth.getBalance(address, function (error, result) {
    if (!error) {
      console.log(result);
    } else {
      console.error(error);
    }
  }).toNumber();
}
```

**Comment by tmashuang** [comment]
Try this:

function getBalance (address) {
  return web3.eth.getBalance(address, function (error, result) {
    if (!error) {
      console.log(result.toNumber());
    } else {
      console.error(error);
    }
  })
}

**Comment by flyswatter** [comment]
Part of the problem is you're treating this `web3` callback method as if it returned a promise. It does not. If you prefer using promises, you should try using `ethjs` instead, although that might confuse you more.

To make your function work, the way you seem to be using this, try this:
```javascript
function getBalance (address) {
  return new Promise (function (resolve, reject) {
    web3.eth.getBalance(address, function (error, result) {
      if (error) {
        reject(error);
      } else {
        resolve(result);
    }
  })
}
```

Another component, is that you seem to be trying to cal `toNumber()` on a `BN` object, and expecting it to fit in a JavaScript number.

One ether is `1x10^18` *wei*, which is the smallest indivisible unit in the Ethereum virtual machine. To convert this number to *ether*, you should call this method:

`web3.fromWei(result, 'ether')`.

This will return a string representation of the ether balance.
