### ISSUE TITLE
Transaction stuck on pending

### ISSUE THREAD

**Issue by winger13** [MetaMask/faq#28]
hi guys

i joined the SNT ICO fun yesterday but my tx didnt go know where with the Transaction still pending! when i click on the link to the Ethereum website i get a ''unable to locate transaction entry'' so iv tried a few more times to send the ETH and nothing. at this point my funds are stuck and unable to move to other wallets. safe to say i missed the ICO boat.

https://etherscan.io/tx/0xec80b796249131f86ee454628d13a78fb7871b2929c4d8478e5702b84e09d754

any help would be great 

thank you

**Comment by winger13** [comment]
now i have this next to my transactions

![capture](https://user-images.githubusercontent.com/29597392/27377768-d312f540-566d-11e7-9ca3-95faf920ce14.PNG)

whats going on ahhhhhh

**Comment by tmashuang** [comment]
The Entire Network is experiencing heavy load right now, due to the Status token launch. If your transactions are pending, and haven't been mined yet, that's probably because the network is backed up. This is not a MetaMask issue, this is an Ethereum issue, it can only process so many transactions at once.  Please be patient, your pending transactions may be successful eventually. There is also a known bug that MetaMask will mark a transaction as "failed" (and say "gave up submitting" when you hover your mouse over it) if it took too long to mine. That is normal today. Just be patient, it may still be mined, but there are no guarantees, there is a huge, unprecedented backlog, no one knows exactly how it will go down.

**Comment by winger13** [comment]
ah ok thanks for clearing that up. so the transaction hasn't necessarily ''failed'' as it appears. it should still go through or at worst get kicked back to my account ? 

thanks

**Comment by tmashuang** [comment]
I would relog using your seed phrase to update the status of those pending Txs. Settings > Lock > I forgot my password.

**Comment by winger13** [comment]
ok i will try that now

**Comment by winger13** [comment]
ok done that still showing failed!

**Comment by tmashuang** [comment]
Until it shows up on etherscan, there is no way for it to confirm it's status. More than likely they are still getting mined.

**Comment by winger13** [comment]
my friend is a miner can i get him to do it manually?

**Comment by tmashuang** [comment]
I don't think that's how it works, but doesn't hurt to ask him.

**Comment by winger13** [comment]
haha no problem thanks for your help, hopefully it goes through. this SNT sale was huge!

**Comment by tmashuang** [comment]
It sure was. Closing for right now. Reopen if this is still an issue.

**Comment by flyswatter** [comment]
If you hover your cursor over the failed message you will see the reason, probably MetaMask gave up transmitting the tx.

Since the sale is now over, you actually probably don't want any of those to be mined, so you should be almost fine.

Try switching your network (top right menu) to another Network and back again. This clears the nonce cache, and should allow you to send transactions again. We're going to improve that nonce tracking soon.
