### ISSUE TITLE
Request: Refund of txn fees

### ISSUE THREAD

**Issue by matwxx** [MetaMask/faq#35]
I spent 0.22 ETH on paying txn fees for 33 attemps on purhasing an ICO and none of them went through. I open an issue ticket to ask why today. It was because I didn't uninstall and reinstall back. There were no instruction showing that I have to do this step to send transaction out before I install your software. This caused me 0.22 ETH on nothing. You should pay me back.

**Comment by frankiebee** [comment]
https://medium.com/metamask/regarding-pending-transactions-4ec0ec23140d

**Comment by Zanibas** [comment]
While it's unfortunate that you've lost ether submitting several transactions, as seen in the post linked above, those transactions not making it through the network was outside of our control. The network went through a very stressful period that pushed its limits. Your transactions were being submitted correctly on our side, but the network simply had too large a backlog to handle your transactions.

However, we are not responsible for users and their actions when they use our software. Although we make our best efforts to protect users as best they can, we cannot refund every user who loses ether through our system, especially considering the problem was outside of our control. Ethereum is still a maturing system and problems are bound to appear--it is your responsibility and risk to handle your ether safely with this in mind. We sympathize with your troubles and we will try to protect future events like this from happening as much as we can, but participating in this ecosystem was a risk that you took.

**Comment by flyswatter** [comment]
Also, the solution you present: uninstalling and reinstalling, would not have solved your situation. That was a solution for users experiencing a totally different issue, namely a nonce cache issue, which was unrelated to the network congestion that caused your transactions to be mined late. If you had transactions successfully mined, you experienced more success than many users. The quantity of transactions you sent was your decision.

Sorry to hear about the loss, many users spent a lot of gas to get in this sale unsuccessfully, and that was just the price for a chance.
