### ISSUE TITLE
Cannot Transfer STORJ Token out  of MetaMask

### ISSUE THREAD

**Issue by snakecrane21** [MetaMask/faq#40]
I was able to transfer tokens of STORJ into MetaMask just fine. But now when I want to transfer them back to my MEW wallet or another exchange it adds 8 decimal places. I type in 351. Then on Etherscan.io it shows up as 0.00000000351?????????? that is some crazy shit right there. What is going on? I need help PLEASE!!! https://etherscan.io/token/Storj?a=0x1a915c3242ac5f65b841e208f36edd1db341ffba

**Comment by shchlolly** [comment]
Same here....let me know if you here anything, please.

**Comment by flyswatter** [comment]
We don't have an official token send page anymore, partly because of precision issues.

As you can see [here](https://etherscan.io/token/Storj), the Storj token has 8 decimals of precision.

What token interface were you using to send? If it was TokenFactory, it's possible it was failing to detect the correct precision. Some older tokens don't actually provide a `decimals` method for auto-detecting this. I recommend using the ethereum wallet interface until MetaMask has an official token send screen. https://wallet.ethereum.org

You can read about other token send options at the bottom of this guide:
http://metamask.consensyssupport.happyfox.com/kb/article/4-managing-tokens

**Comment by snakecrane21** [comment]
I ended up figuring it thankfully weeks ago and don't exactly remember how I did it. What I do is send them to Liqui.io as they were the only exchange trading STORJ tokens. I do remember that I included 8 decimals and giving it enough GAS to push the Tx through.

**Comment by flyswatter** [comment]
That's good to hear. I'll add the storj parameters soon to our token metadata.

**Comment by shchlolly** [comment]
I bought new storj and had it sent to metamask. Just dont know how to transfer or get it out of there.

I will take a look at the link you sent.


Thanks


________________________________

**Comment by shchlolly** [comment]
I was trying to deposit it to etherdelta.


________________________________

**Comment by flyswatter** [comment]
Oh interesting, so this might have been a problem with EtherDelta's STORJ interface.

**Comment by shchlolly** [comment]
Maybe I should choose transfer instead of deposit. As long as the STORJ shows in Metamask it's there?


________________________________
