### ISSUE TITLE
failed transactions and failed EOS token claim

### ISSUE THREAD

**Issue by stether** [MetaMask/faq#44]
With metamask 3.8.1 on Chrome Version 59.0.3071.115  

I get Unexpected end of JSON input wgen tryiing to move ETH from my account in metamask to another account

I also get the following when trying to claim EOS tokens:

SyntaxError: Unexpected end of JSON input

Error: SyntaxError: Unexpected end of JSON input
    at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:8237:28386)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:8238:28122
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:168:7
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:8214:5
    at nrWrapper (https://eos.io/js/monitoring.js:1:11483)

No idea on how to solve.
Thanks.
SS

**Comment by flyswatter** [comment]
Sorry, the network connection issues are because our backend is overwhelmed. The short-term workaround is to point your MetaMask at [a local node](https://github.com/MetaMask/faq/blob/master/USERS.md#using-a-local-node) instead.

You can also try changing the network (top left spinner) to another and back again. Some users have had success with that method.

**Comment by JustinWelshy** [comment]
This is the same issue I'm having but have no idea on how to use a local node - I read the description and am still lost sorry.

I'm not a computer whizz and olny came on here to try to find a solution to this issue,

**Comment by flyswatter** [comment]
Here's a more detailed article on using a local node that I just wrote:
https://consensyssupport.happyfox.com/kb/article/2-using-a-local-node
