### ISSUE TITLE
Accidentally sent ETC instead of ETH to my Metamask account - how can I get it out?

### ISSUE THREAD

**Issue by ciarrocchi** [MetaMask/faq#49]
Hi,
I usually mine ETH and am using my metamask account for that and all is well. I made a mistake last night - I tried mining ETC (Ethereum Classic) and used my metamask account for two transfers of ETC. The transfers went through, it wasn't much, a couple .11 ETC transfers, but the problem is that now I cannot access that ETC. I don't see an Ethereum Classic option in the menu. Is there some way I can access that ETC and send it to some other wallet that I have access to?
My metamask account number is: 0x00B63916Ac44c6F6eCd2e82aF83602726e102065
The transactions of the ETC to my metamask account are these:

0xa3c873bf7f
http://gastracker.io/tx/0xa3c873bf7f2e5ba670289795eaef818bde331080fa70babf4e1b237cbc09510d

and

0x25f65a7063
http://gastracker.io/tx/0x25f65a7063168d5c9d0e7a8de99cdf1e86419d50b72287cc91dba7b56bab0125

Thanks
David

**Comment by flyswatter** [comment]
You can easily export your metamask account private key by clicking the key icon, and then importing it into a wallet that supports ETC.

I believe we're currently incompatible with ETC because of EIP155 compatibility, but since you can easily export a private key, that should do what you want.

Note that since you're now using this account on both chains, you may want to send the ETC through a splitting contract, to prevent any sending of that ether from being replayed on both chains.
