### ISSUE TITLE
faucet.metamask.io don't work

### ISSUE THREAD

**Issue by VKapicyn** [MetaMask/faq#50]
Faucet in Ropsten test-net don't work, it stopped send Ether some hours ago.
https://ropsten.etherscan.io/address/0x81b7e08f65bdf5648606c89998a9cc8164397647

**Comment by Naigel56** [comment]
It seems it has worked since OP posted, but I can't get any test ether. I have a 0 ETH balance address on Ropsten, I request 1 ETH from the faucet, the transaction ID appears but it never really take place.

Address: 0x24eee4c980e4a39bf4b05abd0b7d59691bc3b0dc
Transaction: https://ropsten.etherscan.io/tx/0x9a722fd803ec8c98da22723a49f2103c0cba6b509b47f22021dce47336cb7d4b

I have tried also with a newly generated address but nothing happens

**Comment by kumavis** [comment]
just tested it and it seems to work fine
