### ISSUE TITLE
Handling 'Rejects'

### ISSUE THREAD

**Issue by ropod7** [MetaMask/faq#6]
How to handle transaction 'Reject' in Dapp project?

**Comment by wighawag** [comment]
Currently the only way is to check for errors because user rejection is considered an error for the web3 api.

There is no standard way to check if the error is actually an error or if is the user rejecting the tx.
You could parse the string for a message indicating user rejection but this would be client (metamask) specific

See https://github.com/ethereum/web3.js/issues/531

**Comment by flyswatter** [comment]
Right now the error that MetaMask throws is defined by `web3-provider-engine`'s hooked-wallet subprovider in this line:
https://github.com/MetaMask/provider-engine/blob/7b705b95e8d554cafb12b5973c99323d8e655785/subproviders/hooked-wallet.js#L100

So right now the best way is to check the `error.message` for the string `User denied transaction signature`.

We would be happy to conform to a standard error format as @wighawag [recently suggested](https://github.com/ethereum/web3.js/issues/531).
