### ISSUE TITLE
Why does my password stop working after a few days?

### ISSUE THREAD

**Issue by metamaskwhyyy** [MetaMask/faq#81]
Every few days  my password stops working. I have to keep restoring my wallet from my unlock key and then change password then it works again. I have had no coins stolen or moved so don't understand wtf is going on. Thanks

**Comment by danfinlay** [comment]
Could you tell us a bit about your computer? The model, OS, browser, all might play a role.

This seems very rare, but it seems to happen to some people more than others. My current best guess is that it happens when the computer turns off or sleeps while writing to disk, and it corrupts the metamask storage, but it could be a variety of things.

**Comment by metamaskwhyyy** [comment]
Lenovo, Windows 10, Google Chrome

I did have it installed on two laptops but have uninstalled one one as of today to see if that helps

**Comment by danfinlay** [comment]
Just to confirm, it suddenly doesn't let your password work? What does it say, incorrect password?

Closing in favor of https://github.com/MetaMask/metamask-extension/issues/2515
(That's where we manage bugs. How did you find yourself here, mind if I ask?)
